### ISSUE TITLE
Need help with installation

### ISSUE THREAD

**Issue by WendellAtHome** [emdb-empiar/ahds#2]
Hi! I am having some problems installing this package.
Here is my installed packages list, I followed your requirement for scikit-image, numpy,SimpleParse, and scipy.

![2](https://user-images.githubusercontent.com/39530853/57407122-71446000-71b0-11e9-8fd0-ed83bb3ac4ae.PNG)
![1](https://user-images.githubusercontent.com/39530853/57407153-81f4d600-71b0-11e9-86fd-b1a918f46531.PNG)

**Comment by paulkorir** [comment]
Hi @RealNewNoob ,
Have you tried directly installing the 0.1.8 release? 

`pip install ahds==0.1.8`

It has a windows wheel which I know worked on Windows. Please try and let me know how you have got on. I will aim to have a working 0.1.9 windows wheel available soon.

**Comment by paulkorir** [comment]
Hi @RealNewNoob ,
I've created a python2.7 wheel for v0.1.9. Please try and install it using

`pip install ahds`

I'll close this issue and reopen it if you have any further problem.

Best wishes. 
Paul
