### ISSUE TITLE
is:issue is:open travis not running once again -> travis.org is indicating that it will move to travis.com in a few weeks.  

### ISSUE THREAD

**Issue by hernot** [emdb-empiar/ahds#5]
Not sure how you configured project but travis is not running once again and travis org will migrate. 

Noticed when trying to test my local tox related changses.
=== EDIT
just figured that ahds already has been auto migrated to travis.com and there the log for pullrequests says

```
# dev b2a9765
25 minutes ago
squash if works on travis: changed repo structure to be able to tests proper build of byterele_decoder from c-source in tox virtual environment with pytest. old structure caused import or source and not installed packages
-
Owner emdb-empiar does not have enough credits.
```

Looks ĺike you have to take action to keep things running.

**Comment by paulkorir** [comment]
We're now running on Github Actions. See the `.github` folder for the `yml` file.

**Comment by hernot** [comment]
Not urgent but as you know which changes are necessary, could you also update dev branch if not done anyway. So that i can update pull request which is against dev and not master
